version: "3.5"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  nifi_data:  # Volume lưu dữ liệu của NiFi
    driver: local

services:
  jupyterlab:
    image: pavansrivathsa/jupyterlab
    container_name: jupyterlab
    ports:
      - 4888:4888
      - 4040:4040
      - 8050:8050
    volumes:
      - shared-workspace:/opt/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"

  spark-master:
    image: pavansrivathsa/spark-master
    container_name: spark-master
    ports:
      - 3080:3080
      - 3077:3077
      - 8081:8080
    volumes:
      - shared-workspace:/opt/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"

  spark-worker-1:
    image: pavansrivathsa/spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 4081:4081
    volumes:
      - shared-workspace:/opt/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - spark-master

  spark-worker-2:
    image: pavansrivathsa/spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 4082:4081
    volumes:
      - shared-workspace:/opt/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - spark-master

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://localhost:29092,EXTERNAL://host.docker.internal:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nifi:
    hostname: NiFi
    image: apache/nifi:1.28.0
    build:
      context: .
      dockerfile: Dockerfile.nifi-python
    ports:
      - 8443:8443
    environment:
      - NIFI_WEB_HTTP_PORT=8443
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=2084
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySensitiveKey123!
      
    volumes:
      - nifi_data:/opt/nifi/nifi-current/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
      image: mongo:3.6
      restart: always
      ports:
        - 27017:27017
        
  mongo-express:
    image: mongo-express
    restart: always  
    ports:
    - 4141:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root